from fpdf import FPDF
import os
import textwrap
import re
from datetime import datetime
from typing import Dict, Any

# -------------------------------------------------
# Utility: Remove emojis / unsupported characters
# -------------------------------------------------
def sanitize_text(text: Any) -> str:
    """
    Removes emojis and unsupported characters for PDF safety.
    Keeps ASCII only.
    """
    if text is None:
        return "N/A"
    return re.sub(r"[^\x00-\x7F]+", "", str(text))

# -------------------------------------------------
# Custom PDF Class
# -------------------------------------------------
class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 14)
        self.cell(
            0,
            10,
            "NeuroPulse-MDx+ | AI-Assisted Medical Report",
            ln=True,
            align="C"
        )
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(
            0,
            10,
            f"Generated on {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            align="C"
        )

# -------------------------------------------------
# Section Writer
# -------------------------------------------------
def write_section(pdf: PDF, title: str, content: Any) -> None:
    """
    Writes a titled section safely to the PDF.
    """
    title = sanitize_text(title)
    content = sanitize_text(content)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, f"{title}", ln=True)

    pdf.set_font("Arial", "", 11)
    usable_width = pdf.w - 2 * pdf.l_margin

    for line in content.split("\n"):
        wrapped_lines = textwrap.wrap(line, width=95)
        if not wrapped_lines:
            pdf.ln(5)
        for wrap in wrapped_lines:
            pdf.multi_cell(usable_width, 7, wrap)
    pdf.ln(4)

# -------------------------------------------------
# Main PDF Generator
# -------------------------------------------------
def generate_pdf_report(username: str, result: Dict[str, Any]) -> str:
    """
    Generates a professional medical PDF report.

    Args:
        username (str): Patient username
        result (dict): Dictionary containing symptoms, diagnosis, confidence, AI summary, suggestions

    Returns:
        str: Path to generated PDF file
    """
    pdf = PDF()
    pdf.add_page()

    # Extract data safely
    patient = sanitize_text(username)
    symptoms = sanitize_text(result.get("symptoms"))
    diagnosis = sanitize_text(result.get("diagnosis"))
    confidence = result.get("confidence", "N/A")
    ai_summary = sanitize_text(result.get("ai_summary"))
    suggestions = result.get("suggestions", [])

    # Format suggestions
    formatted_suggestions = ""
    if isinstance(suggestions, dict):
        formatted_suggestions = "\n".join(f"- {sanitize_text(v)}" for v in suggestions.values())
    elif isinstance(suggestions, list):
        formatted_suggestions = "\n".join(f"- {sanitize_text(v)}" for v in suggestions)
    else:
        formatted_suggestions = sanitize_text(suggestions)

    # Write Sections
    write_section(pdf, "Patient Username", patient)
    write_section(pdf, "Reported Symptoms", symptoms)
    write_section(pdf, "AI Predicted Condition", diagnosis)
    write_section(pdf, "Confidence Level (%)", confidence)
    write_section(pdf, "AI Medical Explanation", ai_summary)
    write_section(pdf, "General Health Suggestions", formatted_suggestions)

    # Disclaimer
    pdf.ln(5)
    pdf.set_font("Arial", "I", 9)
    pdf.multi_cell(
        0,
        6,
        "Disclaimer: This report is generated by an AI-assisted system for educational "
        "and support purposes only. It does not replace professional medical consultation."
    )

    # Save file
    filename = f"{patient}_diagnosis_report.pdf"
    output_dir = os.path.join("static", "reports")
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, filename)

    pdf.output(file_path)

    return file_path
